#!/bin/bash
set -e

_link() {
    source=$1
    target=$2
    if [ ! -e $target ]; then
        _run "[link] Install $target" mkdir -p $(dirname $target) \
            && ln -s $source $target
    else
        echo "[link] $target already installed, skipping."
    fi
}
