#!/bin/bash

if [ -z "$__apt_updated" ]; then
    _run "Update APT cache" sudo apt-get update
    __apt_updated=yes
fi

function _apt {
    local pkg=$1
    if ! dpkg -s $pkg >/dev/null 2>&1; then
        _run "[apt] Install $pkg" sudo apt-get install -y $1
    else
        echo "[apt] $pkg is already installed, skipping."
    fi
}
