#!/bin/bash
# Description: Tiling window manager for OSX
set -e

_recipe _launchd
_recipe _link
_recipe brew

_link ${HOME}/dotfiles/.chunkwmrc \
      ${HOME}/.chunkwmrc
_link ${HOME}/dotfiles/.skhdrc \
      ${HOME}/.skhdrc

_brew_tap crisidev/homebrew-chunkwm
_brew chunkwm
brew services start chunkwm

_brew koekeishiya/formulae/skhd
# Use launchd directly rather than brew services so we can configure
# the shell to use bash. There is a significant delay when using zsh
# (my preferred default).
_launchd com.koekeishiya.skhd
