#!/bin/bash
# Description: DOOM Emacs
set -e

_recipe emacs
_recipe git
_recipe _path

# Include japanese language support utilties used by configured packages
_recipe japanese

_git "https://github.com/hlissner/doom-emacs" "$HOME/.emacs.d"
_path "$HOME/.emacs.d/bin"

if ! [ -d ${HOME}/.doom.d ]; then
    _run "[emacs-doom] Install .doom.d" ln -s ${HOME}/dotfiles/.doom.d ${HOME}/.doom.d
fi

_run "[emacs-doom] Refreshing" $HOME/.emacs.d/bin/doom sync
