#!/bin/bash
# Description: GNU Emacs
set -e

_recipe brew

case $_PLATFORM in
    darwin)
        _brew_tap railwaycat/emacsmacport
        _brew emacs-mac --with-modern-icon
        ;;
    linux)
        _recipe _apt
        _ppa kelleyk/emacs
        _apt emacs26
        ;;
esac
