#!/bin/bash
set +e

_recipe brew

case $_PLATFORM in
    darwin)
        _brew emacs --with-cocoa --with-librsvg --with-imagemagick@6
        ;;
    linux)
        _brew emacs --with-librsvg --with-imagemagick@6
        ;;
esac

if ! [ -d ${HOME}/.emacs.d ]; then
    _run "Install .emacs.d" ln -s ${HOME}/dotfiles/.emacs.d ${HOME}/.emacs.d
fi
