#!/bin/bash
# Description: GNU Emacs
set -e

_recipe brew

case $_PLATFORM in
    darwin)
        _brew_tap railwaycat/emacsmacport
        _brew emacs-mac --with-modern-icon
        ;;
    linux)
        _recipe _apt
        _ppa ubuntu-elisp/ppa
        _apt emacs25
        ;;
esac

if ! [ -d ${HOME}/.emacs.d ]; then
    _run "Install .emacs.d" ln -s ${HOME}/dotfiles/.emacs.d ${HOME}/.emacs.d
fi
