#!/bin/bash
# Description: Email syncing tools plus the mu4e client
set -e

_recipe emacs
case $_PLATFORM in
    darwin)
        _recipe brew
        _brew isync
        EMACS=$(which emacs) _brew mu --HEAD
        ;;
    *)
        _recipe _apt
        for dep in \
            build-essential \
                autoconf \
                automake \
                libtool \
                texinfo \
                libgmime-3.0-dev \
                libxapian-dev \
                guile-2.0-dev \
                html2text \
                xdg-utils \
                libwebkitgtk-dev \
                isync
        do
            _apt $dep
        done
        dir=`mktemp -d` && \
            pushd $dir >/dev/null
        echo "[tgz] Fetching mu"
        curl -sL https://github.com/djcb/mu/archive/master.tar.gz \
            | tar xz --strip 1 && \
            echo "[tgz] Configuring mu" && \
            ./autogen.sh >/dev/null 2>&1 && \
            ./configure --prefix=/usr >/dev/null 2>&1 && \
            echo "[tgz] Building mu" && \
            make >/dev/null 2>&1 && \
            echo "[tgz] Installing mu" && \
            sudo make install >/dev/null 2>&1
        popd >/dev/null
        rm -rf "$dir"
        ;;
esac

_run "[email] Creating mail directories" mkdir -p Mail/{Personal,Work,.attachments}
_recipe nvm
_npm imapnotify
