#!/bin/bash
# Description: The Git version control system
set -e

case $_PLATFORM in
    darwin)
        _recipe brew
        _brew git
        ;;
    *)
        _recipe _apt
        _ppa git-core/ppa
        _apt git
        ;;
esac
