#!/bin/bash
# Description: Graphing tool
set -e

case $_PLATFORM in
    darwin)
        _recipe brew
        _brew gnuplot
        ;;
    arch)
        _recipe _arch
        _pacman gnuplot
        ;;
    debian)
        _recipe _apt
        _apt gnuplot
        ;;
esac
