#!/bin/bash
# Description: Graph visualization software
set -e

case $_PLATFORM in
    darwin)
        _recipe brew
        _brew graphviz
        ;;
    arch)
        _recipe _arch
        _pacman graphviz
        ;;
    debian)
        _recipe _apt
        _apt graphviz
        ;;
esac
