#!/bin/bash
# Description: Japanese Language Support
set -e

case $_PLATFORM in
    darwin)
        _recipe brew
        _brew cmigemo
        ;;
    linux)
        _recipe _apt
        _apt kakasi
        _apt cmigemo
        ;;
esac
