#!/bin/bash
# Description: Command-line double-entry accounting
set -e

case $_PLATFORM in
    darwin)
        _recipe brew
        _brew ledger
        ;;
    arch)
        _recipe _arch
        _pacman ledger
        ;;
    debian)
        _recipe _apt
        _ppa mbudde/ledger
        _apt ledger
        ;;
esac
