#!/bin/bash
# Description: File syncing
set -e

case $_PLATFORM in
    darwin)
        _recipe brew
        _recipe _path
        _brew_cask nextcloud
        _path /Applications/nextcloud.app/Contents/MacOS
        ;;
    arch)
        _recipe _arch
        _pacman nextcloud-client
        ;;
    debian)
        _recipe _apt
        _ppa nextcloud-devs/client
        _apt nextcloud-client
        ;;
esac
