#!/bin/bash
# Description: Password Store
set -e

case $_PLATFORM in
    darwin)
        _recipe brew
        _brew pass
        ;;
    *)
        _recipe _apt
        _apt pwgen
        _apt tree
        _apt xclip
        if [ ! -x /usr/bin/pass ]; then
            dir=`mktemp -d` && \
                pushd $dir >/dev/null
            echo "[tgz] Fetching password-store"
            curl -sL https://git.zx2c4.com/password-store/snapshot/password-store-master.tar.xz \
                | tar x -J --strip 1 && \
                echo "[tgz] Installing password-store" && \
                sudo make install >/dev/null 2>&1
            popd >/dev/null
            rm -rf "$dir"
        else
            echo "[tgz] password-store is already installed, skipping."
        fi
esac
