#!/bin/bash
# Description: Password Store
set -e

case $_PLATFORM in
    darwin)
        _recipe brew
        _brew pass
        _brew pass-otp
        ;;
    arch)
        _recipe _arch
        _pacman pass
        _pacman pass-otp
        ;;
    debian)
        _recipe _apt
        _apt pwgen
        _apt tree
        _apt xclip
        _apt oathtool
        _apt zbar-tools

        if [ ! -x /usr/bin/pass ]; then
            dir=`mktemp -d` && \
                pushd $dir >/dev/null
            echo "[tgz] Fetching password-store"
            curl -sL https://git.zx2c4.com/password-store/snapshot/password-store-master.tar.xz \
                | tar x -J --strip 1 && \
                echo "[tgz] Installing password-store" && \
                sudo make install \
                     ZSHCOMPDIR=/usr/share/zsh/vendor-completions \
                     >/dev/null 2>&1
            popd >/dev/null
            rm -rf "$dir"
        else
            echo "[tgz] password-store is already installed, skipping."
        fi
        if [ ! -x /usr/lib/password-store/extensions/otp.bash ]; then
            dir=`mktemp -d` && \
                pushd $dir >/dev/null
            echo "[tgz] Fetching pass-otp"
            curl -sL https://github.com/tadfisher/pass-otp/tarball/develop \
                | tar x -z --strip 1 && \
                echo "[tgz] Installing pass-otp" && \
                sudo make install >/dev/null 2>&1
            popd >/dev/null
            rm -rf "$dir"
        else
            echo "[tgz] pass-otp is already installed, skipping."
        fi
esac
