#!/bin/bash
# Description: Python tiling window manager for X and Wayland
set -e

case $_PLATFORM in
    arch)
        _recipe _arch

        _pacman qtile
        _pacman python-dbus-fast

        _pacman alacritty
        _pacman dunst
        _pacman slock
        _pacman numlockx

        # Automatic display management
        _pacman autorandr # X11
        _pacman kanshi    # Wayland

        _pacman rofi
        _pacman rofi-pass
        _pacman rofi-emoji
        _pacman rofi-calc

        _pacman xfce4-settings # For xfce4-find-cursor
        ;;
esac

for config in qtile alacritty dunst; do
    if ! [ -d ${HOME}/.config/${config} ]; then
        _run "[emacs-doom] Install .config/${config}" ln -s ${HOME}/dotfiles/.config/${config} ${HOME}/.config/${config}
    fi
done
