#!/bin/bash
# Description: Useful command-line utilities
set -e

_recipe _path

case $_PLATFORM in
    darwin)
        _recipe brew

        _brew binutils
        _brew coreutils
        _brew findutils
        _brew gawk
        _brew gnu-indent
        _brew gnu-sed
        _brew gnu-tar
        _brew gnu-which

        # File browsing
        _brew tree
        _brew ncdu

        # File compression
        _brew p7zip
        _brew unrar

        # Misc
        _brew entr
        _brew html-xml-utils
        _brew htop
        _brew jq
        _brew lnav
        _brew the_silver_searcher
        _brew tig
        _brew tmux

        _brew rename
        _brew watch

        # Override BSD tools with GNU variants
        for path in $(gfind /usr/local/Cellar -type d -name gnubin); do
            _path $path \;
        done
        ;;
    *)
        _recipe _apt

        # File browsing
        _apt tree
        _apt ncdu

        # File compression
        _apt p7zip
        _apt unrar

        # Misc
        _apt entr
        _apt html-xml-utils
        _apt htop
        _apt jq
        _apt lnav
        _apt silversearcher-ag
        _apt tig
        _apt tmux
        ;;
esac
