#!/bin/bash
set +e

_recipe brew

case $_PLATFORM in
    darwin)
        _brew binutils
        _brew coreutils
        _brew findutils --with-default-names
        _brew gawk
        _brew gnu-indent --with-default-names
        _brew gnu-sed --with-default-names
        _brew gnu-tar --with-default-names
        _brew gnu-which --with-default-names

        # File browsing
        _brew tree
        _brew ncdu

        # File compression
        _brew p7zip
        _brew unrar
        ;;
    *)
        _recipe _apt

        # File browsing
        _apt tree
        _apt ncdu

        # File compression
        _apt p7zip
        _apt unrar
        ;;
esac

# Misc
_brew htop
_brew tig
_brew lnav
_brew tmux
_brew jq
