#!/bin/bash
# Description: Ubuntu Snaps
set -e

_recipe _apt

_apt snapd

function _snap {
    local package=$1
    if ! snap info $package | grep ^installed: >/dev/null; then
        _run "[snap] Install $package" sudo snap install $@
    else
        echo "[snap] $package is already installed, skipping."
    fi
}
