#!/bin/bash
# Description: Tiling window manager for OSX
set -e

_recipe _launchd
_recipe _link
_recipe brew

_link ${HOME}/dotfiles/yabai/.yabairc \
      ${HOME}/.yabairc
_link ${HOME}/dotfiles/yabai/.skhdrc \
      ${HOME}/.skhdrc

_brew koekeishiya/formulae/yabai

_brew koekeishiya/formulae/skhd
# Use launchd directly so we can configure the shell to use bash (uses a custom
# plist in ../Library/LaunchAgents). There is a significant delay when using zsh
# (my preferred default).
_launchd com.koekeishiya.skhd
skhd --start-service
yabai --start-service
