#! /bin/sh

pgrep -x sxhkd >/dev/null \
    && pkill -x -SIGUSR1 sxhkd \
    || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12
bspc config bottom_padding      30

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config pointer_modifier mod1

bspc rule -r '*'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Cerebro state=floating focus=on
bspc rule -a Emacs state=tiled
