;; -*- mode: emacs-lisp; -*-

(source gnu)
(source melpa)
(source marmalade)
(source org)

(depends-on "color-theme")
(depends-on "magit")
(depends-on "org-plus-contrib")
(depends-on "auto-complete")
(depends-on "git-gutter")
(depends-on "smex")
(depends-on "expand-region")
(depends-on "powerline")
(depends-on "ack-and-a-half")
(depends-on "projectile")
(depends-on "flycheck")

;; Misc
(depends-on "sauron")
(depends-on "weechat")

;; Themes
(depends-on "twilight-theme")
(depends-on "late-night-theme")
;; PHP
(depends-on "php-mode")
(depends-on "web-mode")

;; Python
(depends-on "python")

;; Ruby
(depends-on "rvm")

;; Erlang
(depends-on "erlang")

;; Haskell
(depends-on "haskell-mode")

;; Markdown
(depends-on "markdown-mode")

;; Common Lisp
;; (depends-on "slime")
;; (depends-on "slime-repl")

;; Lisp / Scheme
(depends-on "paredit")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-identifiers")
