; -*- mode: emacs-lisp; -*-
(source "elpa" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "color-theme")
(depends-on "magit")
(depends-on "org")
(depends-on "auto-complete")
(depends-on "git-gutter")
(depends-on "smex")
(depends-on "expand-region")
(depends-on "powerline")
(depends-on "ack-and-a-half")
(depends-on "projectile")
(depends-on "flycheck")

;; Themes
(depends-on "twilight-theme")
(depends-on "late-night-theme")
;; PHP
(depends-on "multi-web-mode")
(depends-on "php-mode")

;; Python
(depends-on "python")

;; Erlang
(depends-on "erlang")

;; Haskell
(depends-on "haskell-mode")

;; Markdown
(depends-on "markdown-mode")

;; Common Lisp
;; (depends-on "slime")
;; (depends-on "slime-repl")

;; Lisp / Scheme
(depends-on "paredit")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-identifiers")
